[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "steroid"
version = "v0.6b"
authors = [
  "Mohammed Al Ameen <ameenmohammed2311@gmail.com>"
]
description = "Steroid"
readme = "README.md"

repository = "https://github.com/struckchure/steroid"
homepage = "https://github.com/struckchure/steroid"

classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = "^3.8"
annotated-types = "0.5.0"
anyio = "3.7.1"
click = "8.1.5"
exceptiongroup = "1.1.2"
fastapi = "0.100.0"
h11 = "0.14.0"
idna = "3.4"
pydantic = "2.0.3"
pydantic-core = "2.3.0"
sniffio = "1.3.0"
starlette = "0.27.0"
typing-extensions = "4.7.1"
uvicorn = "0.23.0"
