[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "aiopypiserver"
version = "0.0.5"
authors = [
    {name="Jamie Walton"}
]
description = "Do what pypiserver does, but with aiohttp."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "aiohttp == 3.8.*"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Environment :: Console",
    "Development Status :: 3 - Alpha",
]

[project.urls]
"Homepage" = "https://github.com/jamie0walton/aiopypiserver"
"Bug Tracker" = "https://github.com/jamie0walton/aiopypiserver/issues"

[project.scripts]
aiopypiserver = "aiopypiserver:commandline_run"
