[tool.poetry]
name = "letterenv"
version = "0.1.5"
description = ""
authors = ["Tristan Bester <tristanbester@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
numpy = "^1.25.1"
gymnasium = "^0.28.1"


[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"
black = "^23.3.0"
flake8-annotations = "^3.0.1"
flake8-eradicate = "^1.5.0"
flake8-docstrings = "^1.7.0"
flake8-isort = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
