[build-system]
build-backend = "setuptools.build_meta"
requires = ['setuptools>=68.0.0']

[project]

name = "fitsviz"
version = "1.2.1"
description = "Autodetection of sources and visualization of FITS files"

authors = [
    {name="Phani Velicheti",email = "phaniv@arizona.edu"}
]

readme = "README.md"
requires-python = ">= 3.8, < 3.12"

dependencies = [
    "pytest==7.1.3",
    'poetry-core',
    'astropy>=5.3.1',
    'bokeh>=3.2.0',
    'click>=8.1.5',
    'dask>=2023.5.0',
    'matplotlib>=3.7.2',
    'numpy>=1.20.1',
    'pandas==1.5.3',
    'scipy>=1.11.1',
    'photutils>=1.8.0',
    'dask[distributed]>=2023.7.0'

]



