[tool.poetry]
name = "app"
version = "0.1.0"
description = "TestNewWithOptionsPypi_P0 backend"
authors = ["Your Name <you@example.com>"]

{{ tool.poetry.source }}
name = "doubanio"
url = "https://pypi.doubanio.com/simple"

[tool.poetry.dependencies]
python = "^3.6"
flask = "^1.1.2"
flask-marshmallow = "^0.11.0"
flask-sqlalchemy = "^2.4.1"
flask-migrate = "^2.5.3"
flask-apispec = "^0.8.8"
Flask-Bcrypt = "^0.7.1"
Flask-Jwt-Extended = "^3.24.1"
marshmallow-sqlalchemy = "^0.22.3"
psycopg2 = {version = "^2.8.5", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.7.9"
pytest-cov = "^2.8.1"
factory-boy = "^2.12.0"
psycopg2-binary = "^2.8.5"

[tool.poetry.extras]
pg = ["psycopg2"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[horn]
directory = "test_new_with_options_pypi___p0"
project_name = "TestNewWithOptionsPypi_P0"
app_name = "app"