# https://peps.python.org/pep-0621/#example

[project]
name = "bcmd"
version = "0.0.6"
description = "Utils commands for Beni"
requires-python = ">=3.10"
keywords = ["benimang", "beni", "bcmd"]
authors = [
  {email = "benimang@126.com"},
  {name = "Beni Mang"}
]
maintainers = [
  {name = "Beni Mang", email = "benimang@126.com"}
]

dependencies = [
  'aioconsole',
  'aiofiles',
  'aiohttp',
  'autopep8',
  'benimang==0.4.4',
  'build',
  'colorama',
  'nest-asyncio',
  'orjson',
  'portalocker',
  'pretty_errors',
  'pyperclip',
  'qiniu',
  'twine',
  'typer',
  'tzdata',
]

[project.scripts]
bcmd = "bcmd.main:run"