[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "libs_n_utils_package_uq_2022"
version = "0.0.5.4"
authors = [
  { name="siamak layeghy", email="siamak.layeghy@uq.net.au" },
]
description = "A small library of utilities"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/layeghy/libs_n_utils"
"Bug Tracker" = "https://github.com/layeghy/libs_n_utils/issues"