[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "security-arbihacker"
version = "0.0.3"
authors = [
    { name="Sergei Aslamazov", email="mrvisioo@gmail.com" },
]
description = "Utils to make setting up API security with FastAPI faster and easier."
readme = "README.MD"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/ArbiHacker/security_arbihacker"
